### ISSUE TITLE
using $(lib.version) in cflags

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd-lib-builder#1]
i would like to pass the automatic variable `$(lib.version)` as a preprocessor define to the compiler.
So i added the following to my *Makefile*:

     cflags = -DMY_VERSION=$(lib.version)

and test it with:

     $ make vars | grep cflags
     variable cflags = -DMY_VERSION=0.1.2

so far so good (*0.1.2* being the version as defined in my `meta`-patch)
unfortunately, during the actual build the `$(lib.version)` is *not expanded*:

     $ make
     [...]
     cc -DUNIX -DPD -I "/usr/include/pd/" -fpic -DMY_VERSION= -Wall -Wextra -Wshadow -Winline -Wstrict-aliasing -O3 -ffast-math -funroll-loops -fomit-frame-pointer -march=core2 -mfpmath=sse -msse -msse2 -msse3  -o foo.o -c foo.c
     [...]

since i'm notoriously bad with make's variable expansion, I'm stuck...

**Comment by umlaeute** [comment]
My current workaround for #1 is to inject the version string directly into `cflags` before including `Makefile.pdlibbuilder` and *not* using `$(lib.version)` at all:

    cflags = -DMY_VERSION=\"$(shell $(SHELL) bin/version)\"

    include $(firstword $(wildcard Makefile.pdlibbuilder ../Makefile.pdlibbuilder))

**Comment by katjav** [comment]
I found the culprit but have to test a few possible fixes.

**Comment by katjav** [comment]
Think I got this fixed in Makefile.pdlibbuilder version 0.0.1. Let me know if it works for you.

**Comment by umlaeute** [comment]
indeed, this seems to fix it.

thanks
