### ISSUE TITLE
arch.cflags on causes FTBFS on armel

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd-lib-builder#14]
just to let you know: the automatic optimization flags for `armv7l` (namely: `-mfloat-abi=hard`) are causing build-failures on Debian's `armel` architecture.

     $ uname -a
     Linux abel 3.16.0-4-armmp-lpae #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) armv7l GNU/Linux

Here is a [build-log](https://buildd.debian.org/status/fetch.php?pkg=pd-cyclone&arch=armel&ver=0.2~beta1-1&stamp=1453715809) for pd-cyclone (0.2~beta1), as maintained by @electrickery  (which does *not* yet use the newest Makefile.pdlibbuilder)

removing any arch-flags as in the following invokation fixes the problem, so it is not a big problem.

     make arch.fags=""

**Comment by umlaeute** [comment]
oops, i just checked.
using the newest `Makefile.pdlibbuilder` fixes the problem (since `CFLAGS` also overwrite `arch.flags`).
i'll report the issue with pd-cyclone.

**Comment by katjav** [comment]
Is it useful to include an armel target definition in Makefile.pdlibbuilder or do you overwrite architecture flags anyhow?

**Comment by umlaeute** [comment]
for Debian i'm overwriting them anyhow.

afaik, the problem with `arm` is that there are so many variants that it is virtually impossible to know what kind of system you are actually running on by just looking at the CPU (e.g. whether the system if configured to support hardfloats).

the defaults are probably fine (considering beagleboard, rpi2,...), and pd-lib-builder allows easy disabling of optimisation flags since #5 has been resolved; so really the problem is that pd-cyclone uses an old pd-lib-builder makefile.
