### ISSUE TITLE
multiple arch builds incompatible with dependency checking

### ISSUE THREAD

**Issue by katjav** [pure-data/pd-lib-builder#16]
Currently Makefile.pdlibbuilder makes fat binaries by default on OSX. A non clean build attempt on OSX (10.5 at least) triggers gcc error because some preprocessor flags are not allowed for multiple architecture builds, amongst them flag -MM which is used for dependency checking.

I don't want to remove dependency checking or disable it by default. Developers expect a build system to do dependency checking and it would be confusing if you need to enable it explicitly.

Alternatively we could build single architecture by default and introduce a make option to build fat binaries.

**Comment by danomatika** [comment]
Since the vanilla builds are ostensibly 32bit & 64bit separately, I feel that could be a reasonable move.

**Comment by umlaeute** [comment]
what i recently found in a few projects (e.g. in JUCE) is:

- have a single variable reserved explicitely for allowing multi-arch
- disable dependency checking if the build is configured for multiple archs.

caveats:
- i'm aware that it was on my request that the `arch.*.flags` are now used for more things than just enabling multiple archs.

@danomatika i don't buy this: are there many *applications* that are built for multi-arch? I assume that the OS will pick the `64bit` version over the `32bit` version - and given that a number of externals are not 64bit ready on OSX (hint, hint, ;-)) using 32bit as the default seems sensible from the "Pd" POV.
that doesn't mean however that externals (that do support both archs) shouldn't be built multi-arch by default.

**Comment by katjav** [comment]
So we could have make option 'fat' which only has meaning when building on OSX. This option would disable dependency checking and build the same things as are now built by default. Only thing is, arch flags need another reorganization. Hopefully no one uses these flags in their scripts? They weren't specified as 'API' variables, but..

**Comment by danomatika** [comment]
>that doesn't mean however that externals (that do support both archs) shouldn't be built multi-arch by default.

Good point.

**Comment by katjav** [comment]
Another approach to the current dilemma would be to filter out the 'fat' flags during dependency checking. Option -MM is used to check non-system headers only. Assuming that dependency checking is mostly relevant for partial rebuilds during development, you wouldn't need multi arch flags for it. A fix along these lines could leave most of current behavior intact: default fat binaries and dependency checking. Another question is: would you want to build fat binaries at all during development?

The arch.*.flags variables need to be reconsidered in any case. On OSX they specify multiple arch builds in a single executable bundle. In other cases it is about tuning a single executable to a processor which represents 'minimum specs' of the target machine. These are different purposes after all. 

Because OSX fat flags must be passed to compiler and linker, these could be defined in a single category 'osxfat.flags' overridable by CFLAGS and LDFLAGS. From here I see different possible routes:

- effectuate osxfat.flags conditionally, when user specifies 'osxfat' as make command argument
- or effectuate osxfat.flags by default for compiling and linking but not for dependency checking

The first route is fairly simple to implement, the second less so. It is already a puzzle to accumulate build flags with the intended override behavior.

**Comment by katjav** [comment]
OSX 10.8 is not affected by the issue as it turns out. I observed it on 10.5. Assuming that old systems are not used for development I disabled dependency checking for fat builds on ppc and i386 with commit eb614fd. This fixes the issue for OSX <= 10.5 in Makefile.pdlibbuilder 0.2.3.

About 10.6 and 10.7 I don't know. If no one reports the same problem for these systems I'll close the issue, and fat-default-or-not can be discussed independently.

**Comment by jonwwilkes** [comment]
A few questions:
1. Is there any practical, officially supported way to compile a fat binary on modern Apple hardware that targets all three of ppc, i386, and x86_64?
2. Is there any practical, officially supported way to compile a fat binary on modern Apple hardware that targets i386 and x86_64?

**Comment by danomatika** [comment]
1. Not really, unless you manually install the 10.6 SDK in *the right place*, but even then there is no guarantee the newer tools will be compatible with it.

2. Yes. AFAIK that is the default behavior.

**Comment by jonwwilkes** [comment]
Well, the pdlibbuilder script fails for me on OSX 10.11.6 with a trivial, single c source library, for the reason cited in this issue title.  This is for Purr Data so I only care about x86_64, but I can't find a way to target only x86_64 without hard-coding changes into the script itself.  No combination of settings for arch.c.flags, arch.ld.flags, and/or disable-dependency-tracking in my lib's makefile will work.

**Comment by katjav** [comment]
> No combination of settings for arch.c.flags, arch.ld.flags, and/or disable-dependency-tracking in my lib's makefile will work.

That is because overriding behavior of make variables is defined per source. It should be possible to override these variables from command line, but not from your makefile.

But of course the issue must be fixed in a structural way. Just to be sure, I assume you can do a clean build, but get an error when trying non clean build (about option -MM not being supported in combination with multiple architecture definitions). Can you paste the error output here? What change in the script avoids the error?

**Comment by jonwwilkes** [comment]
Error output:
```
clang: error: cannot use 'dependencies' output with multiple -arch options
Makefile.pdlibbuilder:916: *** missing separator.  Stop.
```

Removing `-arch i386` solves the problem.

Btw-- I don't see `bundle-loader` in the output of the cc command from pdlibbuilder.  Is it not needed?

**Comment by katjav** [comment]
The error text is different than I remember from OSX 10.5 but clearly the same issue (which didn't exist in 10.8) has reappeared, who knows in which OSX version. So the quick fix from commit eb614fd is useless. It seems we must abandon one of two default behaviors ('fat binaries' or 'dependency checking'), or else we could skip dependency checking all together in the preprocessor phase. None of these fixes is really trivial.

**Comment by umlaeute** [comment]
given that the vast majority of Pd-externals are small projects, it's probably reasonable to disable dependency tracking for now.

(i'd actually favour disabling fat binaries, if this wouldn't produce binaries by default that are not usable by most people).

**Comment by jonwwilkes** [comment]
You could make the x86_64 machines build only with `-arch x86_64` and make the i386 machines build fat binaries.  Further, turn off dependency checking on the old machines (those devs are probably used to looong build times anyway), and leave it on for x86_64 machines.

You'll most likely have to do this anyway at some arbitrary date in the future.  A company that removes the mini jack because of "courage" isn't going to keep the old arch around just for poor artists.  (And poor artists couldn't have afforded an Apple machine ten years ago, anyway.)

**Comment by umlaeute** [comment]
having different build profiles per architecture seems like good old cruft.

**Comment by umlaeute** [comment]
anyhow, to reiterate i still think that we could live without dependency tracking: it is *only* needed for rebuilding anyhow

**Comment by danomatika** [comment]
>to reiterate i still think that we could live without dependency tracking

I agree. I'd favor the ability to build fat over depends.

**Comment by katjav** [comment]
A few notes on dependency checking before we drop it (as a default or altogether).

1. 'Dependency checking' means 'implicit dependency checking' in this context, it is about non-system header files.

2. Implicit dependencies are evaluated and stored in memory by Makefile.pdlibbuilder, not written in files.

3. Implicit dependencies are only evaluated by Makefile.pdlibbuilder if a rebuild is detected (presence of build products).

4. This means that implicit dependencies are evaluated for each rebuild.

5. Without implicit dependency checking you get the 'nothing to be done' after a change concerning a header file.


Personally I find dependency checking super important for development. I hate to see 'nothing to be done' when a rebuild is clearly needed. The whole purpose of make is to check if files are up to date, and if not, execute commands to (re)build them. I've spent much effort to get implicit dependency checking right. It isn't done for clean builds because it can be CPU intensive. But it is done in memory for every rebuild because dependency files can get outdated too and become another source of confusing errors.

But the current issue makes dependency checking counterproductive on OSX now that you can't do a rebuild at all. Who knows how many people habitually hit the 'clean button' after every failed build because the makefile doesn't do what we may expect. This needs to be fixed soon. But with the smallest possible damage to existing functionality.

My preference would be to keep dependency checking as default behavior and make fat binary optional (which then disables dependency checking). This seems most consistent with expected behavior of a build system. A variable 'fat', only valid for Darwin and empty by default, could define target architecture(s) ppc / i386 / x86_64. Definition of this variable in an including makefile should be supported, to accommodate centralized build systems like in purr-data.

**Comment by jonwwilkes** [comment]
"Who knows how many people habitually hit the 'clean button' after every failed build because the makefile doesn't do what we may expect."

It's probably easier to count the people who haven't done that before. :)

**Comment by electrickery** [comment]
On 2016-09-16 03:19 AM, jonwwilkes wrote:
> "Who knows how many people habitually hit the 'clean button' after every
> failed build because the makefile doesn't do what we may expect."
> 
> It's probably easier to count the people who haven't done that before. :)

Excluding all people who haven't seen a compiler at all, yes.

There are several types of building:
- new development; dependency checking here is useful,
- porting; usually clean builds, so no dependency checking needed,
- bug fixing; dependency checking here is very useful.

Dependency checking is useful in the majority of these set of cases.
Only in the porting case creating fat binaries are more important. This
can be solved with an extra argument which disables dependency checking?

Fred Jan

**Comment by danomatika** [comment]
I'd say approach this in a similar manner to homebrew (an OS X package manager):

* like Xcode, default to build for the current architecture ie. x86_64
* enable building "fat" or "universal" when explicitly asked ie. x86_64 & i386
* if building "fat", check if the compiler accepts ppc and add it if so
* if building "fat", disable dependency checking

This is basically the approach to OSX we're using in the autotools updates to the predate source code, minus the depends checking.

**Comment by katjav** [comment]
What I understand from file universal.m4 in https://sourceforge.net/p/pure-data/pure-data/ci/master/tree/m4/universal.m4 is:

- build for current architecture by default
- support configure option '--enable-universal=\<ARCHS>'
- if option '--enable-universal' is passed but '\<ARCHS>'  is empty, build for all available architectures

This seems to me the best approach indeed. However for simplicity I'd rather like to omit functionality to test which architectures are available. My proposal would be:

- build for current architecture by default
- enable argument 'fat=yes' to build for i386 & x86_64
- enable argument 'fat=\<ARCHS>' to build for specified archs

The 'fat=\<ARCHS>' is then for experts who know what they're doing. On old OSX versions with gcc you could specify not only 'ppc' but also subtypes like 'ppc7400'. I don't consider it a task for Makefile.pdlibbuilder to be knowledgeable about those options, the documentation of which is even hard to retrieve. If architectures are specified but not available, the compiler will warn soon enough.

If there's consensus about this proposal I'll implement it.

**Comment by danomatika** [comment]
That sounds good to me.

**Comment by katjav** [comment]
Commit 3a21fd4 on branch 'optionalfat' implements the above and is tested to work for OSX 10.5. Later I can check OSX 10.8. @jonwilkes, can you check if it works for your case? If no one has objections I'll document it and merge into master.

**Comment by danomatika** [comment]
A quick test on 10.11 with the helloworld example is working:

* _make_ & _file helloworld.pd_darwin_ yields:
~~~
helloworld.pd_darwin: Mach-O 64-bit bundle x86_64
~~~

* _make fat=yes_ & _file helloworld.pd_darwin_ yields: 
~~~
helloworld.pd_darwin: Mach-O universal binary with 2 architectures
helloworld.pd_darwin (for architecture i386):  	Mach-O bundle i386
helloworld.pd_darwin (for architecture x86_64):	Mach-O 64-bit bundle x86_64
~~~

**Comment by danomatika** [comment]
Also, similar to how the pd --universal flag works, I can build just 32 bit via:

* _make fat="i386"_:
~~~
helloworld.pd_darwin: Mach-O bundle i386
~~~

Note, if you're comparing to the pd build system, see the [autotools_updates branch](https://github.com/pure-data/pure-data/tree/autotools_updates) with it's inherent improvements. It's pretty much done, I just need to restart talk about it.

**Comment by katjav** [comment]
Thanks for testing, @danomatika. I wonder if devs normally use a native Pd build on OSX? If many use the i386 build it wouldn't be so useful to have the native build of externals as default.

**Comment by danomatika** [comment]
Well, part of the autotools_updates is to build for native arch by default... aka drag Pd kicking and screaming into 64bit, hopefully.

**Comment by katjav** [comment]
Dropping the fat binary default from Makefile.pdlibbuilder will require some re-education anyhow because for distributions it remains the preferred build. Still I think it's good to proceed this way. Native build is what you'd expect from a build system if nothing specified explicitly. The fat binary default was a disputable choice right from the start (my fault), and will continue to be so until we get rid of it.

**Comment by danomatika** [comment]
Right. My thinking with the autotools_updates was to simply match when has been established practice on OS X for a while now. At this point, the Pd ecosystem could/should be largely 64bit on OS X and it was really only Pd-extended being 32bit that held that back.

**Comment by katjav** [comment]
What I meant to say is, fat binary (32/64 bit) remains the preferred build for distributions of externals at least until all external libs can work with 64 bit Pd.

**Comment by danomatika** [comment]
My 2 cents: They should update (and should have long ago). :)

**Comment by katjav** [comment]
What about GEM, isn't it the main reason to stay with Pd 32 bit on OSX for the moment?

**Comment by danomatika** [comment]
GEM needs to be updated, pure and simple. I started digging into that but it's slipped pretty low on my list since I really don't use GEM for my own work.

My suggestions are only suggestions, but I do know that whatever is set as the default will probably be harder to change later on.

**Comment by katjav** [comment]
I agree that it's better to do a logical thing that is temporarily inconvenient than do an illogical thing that is temporarily convenient. Sure we shouldn't set i386 as default on OSX (it's bad enough that we have this for Windows).

But I'm starting to realize that it may be too early to get rid of the fat binary default. It would cause a lot of confusion when the new default builds x86_64 while most people still use i386 Pd. Sure you can explain there is an option to build fat binaries, but when everyone starts using that option 'by default', they still have no dependency checking and all the fuzz is for nothing.

Is there an alternative solution to the current issue? I'm now thinking of this:

- support easy definition of target architecture(s), but
- keep the fat binary default at least until GEM is x86_64-ready for OSX
- disable dependency checking for multiple-architecture builds 
- issue a warning when dependency checking is disabled

In fact this is a small amendment on the previous idea. The variable needs renaming too, because it doesn't sound logical if you can define 'fat=i386'.

**Comment by danomatika** [comment]
Yeah, I agree with this reasoning as well. In this light, sticking with a fat lib for now means at least everyone can still use what is built. You're right in that we want to move things forward but without unnecessarily breaking changes.

In regards to the naming, maybe "universal" makes more sense. This is what home-brew uses ala:

    brew install portaudio --universal

builds portaudio for both i386 and x86_64.

The similarly-named option for the puredata configure takes arguments as well. In this vein it is not as logical either, but it's what we have for now...

    ./configure --universal="i386"

yields a 32 bit build.

**Comment by katjav** [comment]
With commit 9fd1795 on branch master I've made a small compromise to dependency checking functionality. Architecture-dependent flags are no longer passed to the preprocessor for dependency checking. The preprocessor will consider the native architecture (as specified in the predefined macros) when evaluating dependencies. Imagine an architecture-dependent include directive like:

```
#if defined(__powerpc__)
#include "ppc_optimizations.h"
#endif

```

File 'ppc_optimizations.h' isn't considered a dependency when cross compiling for ppc on x86_64. But, since dependency checking is mainly important during development and not for cross compilation, this doesn't matter so much. However, architecture-dependent optimization macros are not always predefined. Imagine code like this:

```
#if defined(__SSE__)
#include "sse_optimizations.h"
#endif

```

Without explicit flag, gcc doesn't set '__SSE__ 1' in the predefined macros on Linux, so in that case "sse_optimizations.h" will be overlooked during dependency checking.

With the current compromise, dependency checking works for all header files unconditionally included, also when building fat binaries or cross compiling otherwise. That covers a vast majority of cases. For conditionally included header files dependency checking may fail. I didn't not find a transparent way to leave or filter out only _multiple_ architecture flags while keeping required overriding behavior. But I may find one later. In any case, the issue with rebuilding on OSX should be resolved in Makefile.pdlibbuilder 0.2.6 in the main branch.

**Comment by katjav** [comment]
Can anyone do a quick check with target 'depend' using Makefile.pdlibbuilder 0.2.6 on OSX 10.11? 

I'll continue work on the OSX arch stuff but it should be an orthogonal topic now.

**Comment by danomatika** [comment]
Seems fine.

~~~
$ make
...
$ file helloworld.pd_darwin
helloworld.pd_darwin: Mach-O universal binary with 2 architectures
helloworld.pd_darwin (for architecture i386):  	Mach-O bundle i386
helloworld.pd_darwin (for architecture x86_64):	Mach-O 64-bit bundle x86_64
~~

&

~~~
$ make depend
++++ info: using Makefile.pdlibbuilder version 0.2.6
++++ info: making target depend in lib helloworld
++++ info: generated prerequisite rules
helloworld: helloworld.pd_darwin
helloworld.pd_darwin: helloworld.o
./helloworld.o: /Applications/Pd-extended.app/Contents/Resources/include/pdextended/m_pd.h  Makefile pd-lib-builder//Makefile.pdlibbuilder
~~~

**Comment by katjav** [comment]
Thanks again for testing, @danomatika. Seems this issue can be closed. I'll open a separate issue on the question if / when to remove the fat binary default.

Good point about the search pattern, yes every issue should be discussed in its own thread.

**Comment by katjav** [comment]
So far no negative response on commit 9fd1795, let's consider this issue fixed. Closing now.
