### ISSUE TITLE
target 'post' forces rebuild of executables

### ISSUE THREAD

**Issue by katjav** [pure-data/pd-lib-builder#17]
Commit c428456 (following up on pull request #4) introduced targets 'pre' and 'post' to be run before and after target 'all'. Turns out that target 'post' forces rebuild of executables (linking the .o files) even when .o files haven't changed. It was declared as phony target, but even without that it still acts as such, probably because 'post' is not a file so make can't compare timestamps.

While it is not a show stopper, this behavior can be very annoying when developing or bug fixing files in a large collection. Currently I don't see a solution.

**Comment by katjav** [comment]
Turns out that target 'pre' is the culprit. Executables depend on it to make sure that 'pre' is done first:

    $(executables): pre

Quoting from Robert Mecklenburg's 'Managing Projects with GNU Make' (chapter 2):

> Phony targets are always out of date, so they always execute and they always cause their dependent (the target associated with the prerequisite) to be remade.

So here's the problem and what's worse, it doesn't even guarantee correct order of operations. If the current method seems to work it is by chance. To really make sure that 'pre' is executed before the build begins, the object files should depend on it and not the executables:

    file1.o file2.o:  pre
   
As is now obvious, this would force the object files to be remade. In other words the whole build.

Target 'pre' must be removed from Makefile.pdlibbuilder because it compromises functionality for every user, no matter if they actually employ the 'pre' target or not.

**Comment by katjav** [comment]
When target 'pre' will be removed from Makefile.pdlibbuilder, this is a simple alternative to be written in the library makefile (tested):

    ....
    
    include Makefile.pdlibbuilder
    
    $(all.objects): pre
    
    pre:
        @echo "this target is made first of all"


It is more flexible. You can choose a target name, it can be a real file too. And the rule could be defined as double colon if needed. As a matter of fact this method is already possible with current Makefile.pdlibbuilder since variable 'all.objects' has always been there for other purposes.

**Comment by katjav** [comment]
@umlaeute, I need your opinion on this topic since you proposed the pre and post targets and maybe you use it in practice. I want to remove pre (but not post) from Makefile.pdlibbuilder. There is a good alternative method, see comment above. 

Removal potentially breaks compatibility with current makefiles. For that reason, do you think the major version number should be updated? It follows semantic versioning (http://semver.org/).

**Comment by umlaeute** [comment]
Go ahead with removing it.

The workaround you propose is sane enough to be used whenever this id really needed.

**Comment by katjav** [comment]
Target 'pre' is removed with commit d94538e.

**Comment by katjav** [comment]
Commit c989c8e updates version number for this bug fix: 0.2.2.
