### ISSUE TITLE
specifying a given m_pd.h file

### ISSUE THREAD

**Issue by porres** [pure-data/pd-lib-builder#23]
howdy, seems pd-lib-builder will automatically search and find for a pd-extended in your system to build classes, but I'm using new stuff from new vanilla. The way I'm doing it is that i'm replacing files in extended by the new vanilla ones, but there's gotta be a better way that either exists and I dont know about or that we'd have to create.

I was thinking of a way to specify in the makefile which files to use in a subfolder or something, then I could have it in some of my projects subfolder.

cheers

**Comment by danomatika** [comment]
Try `make help` ...

**Comment by porres** [comment]
ok... found this :) 

------------------------------------------------------------------------
++++ info: making target help in lib cyclone

  Main targets:
    all:     build executables (default target)
    install: install all components of the library
    vars:    print makefile variables for troubleshooting
    allvars: print all variables for troubleshooting
    help:    print this help text

  Pd API m_pd.h:
    /Applications/Pd-extended.app/Contents/Resources/include/pdextended/m_pd.h
  You may specify your preferred Pd include path as argument to
  the make command, like 'pdincludepath=path/to/pd/src'.

  Path for installation of your libdir(s):
    /Users/sp/Library/Pd
  Alternatively you may specify your path for installation as argument
  to the make command, like 'objectsdir=path/to/pd-externals'.

  Default paths are listed in the doc sections in Makefile.pdlibbuilder.
------------------------------------------------------------------------

thanks

**Comment by porres** [comment]
oh, maybe include this project in the readme as an example of the ones using the Makefile.pdlibbuilder approach?

 https://github.com/porres/pd-cyclone

**Comment by danomatika** [comment]
Done.
