### ISSUE TITLE
(priority of) standard search path for pd includes

### ISSUE THREAD

**Issue by katjav** [pure-data/pd-lib-builder#25]
Variable 'pdincludepath' stores a path to pd API headers (m_pd.h etc.) needed for compilation. If not specified as make command argument, the first path found from the following standard list is used:

1. $(externalsdir)../pd/src
2. pd include path of an installed Pd-extended package
3. pd include path of an installed Pd package

This order of priority was determined at the conception of Makefile.pdlibbuilder more than a year ago, facilitating the transition between centralized and decentralized model of lib development.

The search list needs to be reconsidered now. I guess Pd-extended's unmaintained API should removed from the defaults list so no one can build or develop unintentionally against it.

**Comment by brbrofsvl** [comment]
Switching the order of extended and vanilla could also work, since we still have devoted Pd-extended users. There are problems either way, I guess. 

Thanks for being willing to address this.

Matt

**Comment by umlaeute** [comment]
the Pd-extended zealots can still set the `pdincludepath` to intentionally build against that API.

**Comment by katjav** [comment]
It seems reasonable to keep vanilla (installed package) as the only default to search for, because:

1. vanilla is actively maintained
2. currently most pd lib authors develop against vanilla
3. unlike other pd flavors, vanilla is not part of a centralized build system with internal include path

**Comment by danomatika** [comment]
👍

**Comment by brbrofsvl** [comment]
Yes, this is convincing. Thanks!

**Comment by porres** [comment]
👍 (+1)  totally agree :)

**Comment by katjav** [comment]
Thanks for the discussion. Implemented with commit a6a89dc on branch master. I've only tested on Linux, hopefully no typos in the other platform sections, please test before we close this issue.

Makefile.pdlibbuilder version 0.2.7 will only search for vanilla's standard include path (and in the case of Windows, also executable path). Standard paths per platform are thus:

Linux:         /usr/include/pd
OSX:          /Applications/Pd*.app/Contents/Resources/src
Windows:  %PROGRAMFILES%/pd/src and %PROGRAMFILES%/pd/bin    

To build against something else (another pd flavor, or a newer vanilla than installed), paths need to be defined explicitly as make command argument.

**Comment by katjav** [comment]
No problems reported since commit a6a89dc, closing this now.
