### ISSUE TITLE
no uniform naming scheme for important variables ('PD_PATH', 'objectsdir')

### ISSUE THREAD

**Issue by katjav** [pure-data/pd-lib-builder#27]
Variable names in makefiles should be consistent and intuitive, in particular those which are meant to be used as make command arguments. Unfortunately, a few important Makefile.pdlibbuilder variables are inconsistent in various ways. Consider 'PD_PATH' and 'objectsdir', variables to hold a path to a directory. They are passed as arguments from pd-extended's central makefile to lib makefiles, and 'inherited' by Makefile.pdlibbuilder for compatibility. But the variable names are hard to memorize because:

1. - one is upper case, the other lower case
2. - one has an underscore, the other not
3. - one speaks about path, the other about directory

Regarding upper / lower case, these are the general guidelines I try to follow:

- upper case for standard flag categories (like CFLAGS) and utilities (like CC), plus DESTDIR
- lower case for variables defined by the makefile(s)

See https://www.gnu.org/software/make/manual/html_node/Makefile-Conventions.html. A makefile must honour CFLAGS, CC, DESTDIR etcetera, but not define them or at least allow them to be overridden from the environment because people expect that. Variables for paths (like 'prefix' and 'libdir'), should be in lower case and defined by the makefile. DESTDIR is an exception, a path component used for staged install.

Our variable 'objectsdir' defines a path to the root directory of installed pd libs and is an alias for 'pkglibdir', which in turn is a conventional name. Although 'objectsdir' is unfortunately not an apt name for a directory with _libraries_, at least it follows the lower case convention.

Variable PD_PATH in pd-extended's central makefile defines the path to the pd root dir inside the centralized build system. The Makefile Template has platform dependent PD_PATH definitions. Why uppercase? The Makefile Template has upper case for most (but not all) makefile-defined variables, I can't see a rule behind it.

What about the path / dir distinction? A path is a trajectory in the file system, leading to a directory or file. The meaning of 'directory' is ambiguous. It is often used to denote 'folder', more highlighting the content aspect than the trajectory aspect. Therefore I liked 'path' better initially, and implemented variables 'pdincludepath' and 'pdbinpath' analogous to 'PD_PATH' but leaving away the upper case and underscore. In retrospect I regret my choice for 'path'. Canonical names like 'includedir' and 'libdir' all specify directories with the meaning of paths, not folders. I should better have followed makefile conventions than etymological considerations. Then we could have had a coherent variable set like this:

- pddir: path to pd root dir 
- pdincludedir: path to pd includes dir (where the pd API files are)
- pdbindir: path to pd binary dir (where the pd executable is)
- pdlibdir: path to pd libraries root dir

Much easier to memorize. 'PD_PATH' and 'objectsdir' could have been implemented as aliases. But... aliases are still possible of course.

**Comment by katjav** [comment]
I see an opportunity to improve functionality while introducing better naming consistency: path variables that are all settable in the environment. Written in upper case to reflect their overriding behavior:

- PDDIR: path to pd root dir
- PDINCLUDEDIR: path to pd includes dir (where the pd API files are)
- PDBINDIR: path to pd binary dir (where the pd executable is)
- PDLIBDIR: path to pd libraries root dir

Proposed implementation in branch 'dirs' with commit b0dab72, and commit cf04da9b for updated API description in the makefile. Old path names are still supported but deprecated as user variables.

I'm personally very happy with this approach. Include path and/or installation location can be set in environment so you don't need to type it every time. Paths can also be exported from a root makefile to submakes which is useful in centralized builds a la extended or other multi-lib projects. These conveniences make an attractive switch to new variable names. Plus, the API overview in the makefile gained comprehensibility.

**Comment by danomatika** [comment]
I agree. Env variables work both on the make command line and in the general environment. Simplest is usually best IMO.

**Comment by katjav** [comment]
@umlaeute, I'd like to know your opinion as well on the proposed path variables (upper case and overridable from environment). Do we overlook a possible downside? I wouldn't want to introduce more API variables that are regretted later. If OK I'll merge and document in README.md.

**Comment by katjav** [comment]
Merged commits b0dab72 and cf04da9 in master, then tagged as v0.4.0. But I forgot to document in the README before tagging, bah. Makefile internal documentation is updated though.
