### ISSUE TITLE
-fpic vs -fPIC

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd-lib-builder#29]
I recently stumbled across a build-failure due to the use of `-fpic` in the pd-lib-builder.

This was on a not-so-common architecture (s390x).
The full failing build-log can be found [here](https://buildd.debian.org/status/fetch.php?pkg=pd-ableton-link&arch=s390x&ver=0.2-1&stamp=1477997927).

Replacing `-fpic` with `-fPIC` (upper-case) fixed the problem (replacing the compiler-flags was enough, btw)

So i wonder: why is pd-lib-builder using `-fpic` instead of `-fPIC` in the first place? (it seems that the latter is far more widespread).

**Comment by umlaeute** [comment]
so i found [this on stackoverflow](http://stackoverflow.com/questions/3544035/), which suggests that the difference between the two variants are:
- `-fPIC` will always (that is: on all architectures) work
- `-fpic` might generate smaller and faster code

it also suggests that the *smaller and faster code* promise might only be relevant on *some* architectures, and that on `x86_64` the result will actually be identical. (it would be interesting to know about any differences on `i386`).

given that, i would suggest to switch to `-fPIC`

**Comment by electrickery** [comment]
On 01-11-16 19:55, umläute wrote:
> so i found this on stackoverflow
> <http://stackoverflow.com/questions/3544035/>, which suggests that the
> difference between the two variants are:
>
>   * |-fPIC| will always (that is: on all architectures) work
>   * |-fpic| might generate smaller and faster code
>
> it also suggests that the /smaller and faster code/ promise might only
> be relevant on /some/ architectures, and that on |x86_64| the result
> will actually be identical. (it would be interesting to know about any
> differences on |i386|).
>
> given that, i would suggest to switch to |-fPIC|

A quick test on an i386 Debian shows no difference in size. -fpic occurs 
several times and I changed them all to -fPIC. But these were all small 
single-object files.

Greetings,

Fred Jan

**Comment by katjav** [comment]
fpic/fPIC is one of those things I do not really understand. It is for dynamic link libraries, not dynamic load libraries. But in the build log it is not the shared object that fails to build.

@umlaeute, did you never have the same problem with iemnet, which also builds a shared library? Maybe the difference is because abl_link is C++11 code and the C++ compiler is more critical.

Anyhow I've probably followed a wrong recommendation when using 'fpic'. If it is true that fPIC always works that should be the obvious choice so I'll change it.

**Comment by katjav** [comment]
Changed to fPIC with commit 426b38b.

**Comment by umlaeute** [comment]
- i indeed never had the problem with iemnet.
- the build log of abl_link i referred to, did *not* build a shared-library (`libabl_link~.so`), but instead created a single `.pd_linux` from two object files (this is different from what upstream does; i couldn't really understand why they would use a shared library for a single-object; and [abl_link~-v0.2](http://puredata.info/Members/ant1r/software/abl_link~/0.2/abl_link~-v0.2-(Sources)(Linux-amd64-64)-externals.tar.gz)) as uploaded to deken, completely lacks a build-system.

afaiu, with `-fPIC` the number of visible symbols can be larger than with `-fpic`, and that my build-problem indeed hit this limitation.
most likely we hit this limitation because the two C++ files are combined into a single library and i think that `C++` creates more symbols on the fly, thus exposing the problem earlier.

it *could* be that upstream (ping @nettoyeurny) uses a shared library exactly because combining the two object files fails with `-fpic`.

**Comment by katjav** [comment]
You built with a patched makefile? That explains part of my confusion as I was looking at the upstream makefile.

The other part is, from gcc docs (https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html) I got the impression that the -fPIC is for cases of dynamic linking, which I understand as a shared library.  But in this case it seems that -fPIC is needed for a dynamic load lib ('plugin') after all.

Well let's assume -fPIC is ok in all (Linux) cases.

**Comment by umlaeute** [comment]
yes, I built with a [makefile from scratch](https://anonscm.debian.org/cgit/pkg-multimedia/pd-ableton-link.git/tree/debian/build/Makefile).

**Comment by katjav** [comment]
Ah a glimpse in debian package maintainer's kitchen.

Have you seen the debian package working? I don't mean the s390x build of course. It seems that abl_link_instance is supposed to provide a shared pointer to the global Link instance (the Ableton thing), or create a new instance if necessary. Maybe that is why abl_link_instance should be instantiated only once?

**Comment by santphina** [comment]
What is the advantage of using -fPIC or -fpic for compiling?

**Comment by Spacechild1** [comment]
PIC means "position independent code". You almost always want this for shared libraries. So if you build with `-shared` on Linux, also provide `-fPIC`, unless you have a good reason not to.

**Comment by umlaeute** [comment]
> What is the advantage of using -fPIC or -fpic for compiling?

the main advantage is, that it works on `x86_64` (and probably other archs as well), not just `i386`.
