### ISSUE TITLE
for{Linux,Windows,Darwin} should not use uname

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd-lib-builder#31]
to use OS-specific sets, pd-lib-builder provides the for* mechanism

~~~make
ifdef forWindows
   ldflags += -lws2_32
endef
~~~

unfortunately, this doesn't work when cross-compiling (manually adding `system=Windows`), because the `for*` defines are evaluated based on the output of `uname`.

instead i think the `for*` variants should be expanded based on the value of `system`.

**Comment by katjav** [comment]
Fixed with commit 2c14110.
