### ISSUE TITLE
pd 0.48-0 not automatically found for files like m_pd.h

### ISSUE THREAD

**Issue by porres** [pure-data/pd-lib-builder#33]
pd 0.48-0 is out, and apparently there was a change in the filesystem structure. So we need an update here so it automatically finds it

cheers

**Comment by katjav** [comment]
@porres, can you provide details? Pd repository (https://sourceforge.net/p/pure-data/pure-data/ci/master/tree/) has src/m_pd.h  like it used to be.

**Comment by porres** [comment]
This is how the new Pd is in my mac... the "src" doesn't exist anymore, and header files are located into a "include" folder

<img width="884" alt="screen shot 2017-08-14 at 11 23 49" src="https://user-images.githubusercontent.com/5360142/29275911-29bd2eca-80e3-11e7-8b5b-3c01ea9df528.png">

**Comment by danomatika** [comment]
Hah yeah. You can blame me for this. The new app bundle build script doesn't;t copy the entire contents of the build tree anymore, only the stuff that is actually needed. So instead of putting the whole `src` in Resources, the headers rare put into the ore standard `include` directory.

**Comment by porres** [comment]
yeah, I like that it's cleaner now... those who need the source code in its entirety still know where to find it :)

**Comment by katjav** [comment]
So you can no longer rebuild Pd within the app bundle? This feature was recently advertised by Miller during PdCon16~: https://www.youtube.com/watch?v=cAWFk1PPTtk (around 10:00). Of course this is not the place to dispute the decision to stop embedding the sources but I'm puzzled.

**Comment by danomatika** [comment]
First I've heard of it. All of my focus was on making it easy to build from source at that time.

**Comment by danomatika** [comment]
Opened an issue on this: https://github.com/pure-data/pure-data/issues/181

**Comment by katjav** [comment]
Opened a thread on pd-dev list with a short explanation of the background: https://lists.puredata.info/pipermail/pd-dev/2017-08/021226.html

**Comment by danomatika** [comment]
Also, to provide some perspective, I had written the script 6 months before the pd con. I was there during the announcement but I didn't put two and two together. Oh well, that's why we have `-1` releases.

**Comment by katjav** [comment]
It's just bad luck this didn't come up in the test phase. Whether the src dir will come back in app bundles or not, we now have two possible paths for OSX, depending on Pd version. So I guess we'll have to probe for both. The extra clutter in pdlibbuilder isn't the worst thing about that, but the fact that all external libraries defining the API path are forced to update their build script. Is there no other way out?

**Comment by danomatika** [comment]
> Is there no other way out?

Change `Resources/install` dir back to `Resources/src` in the script.

**Comment by umlaeute** [comment]
@katjav i'd wait and see whether Resources/src comes back in `0.48-1`. If it does, then i would consider the `0.48-0` release a bug and not worry (hey, what would happen if that release had completely omitted the header-files)?

**Comment by rnkn** [comment]
@danomatika f.w.i.w. I appreciated your decision to use the `/include` path.. it corresponds with `$ man hier`.

**Comment by katjav** [comment]
@danomatika what is the status quo of this issue in Pd 0.48-1? Is there a `src` dir or should pdlibbuilder be changed to search for `include`? I'd like to decide before we release an update with the changes from issue #38.

**Comment by danomatika** [comment]
There is a src directory as before.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by katjav** [comment]
Great, thanks. @porres, is this issue solved for you with Pd 0.48-1?

**Comment by porres** [comment]
all works fine, already included pdlibbuilder 0.5.0 in cyclone and else

**Comment by katjav** [comment]
Good. @danomatika, as an aside, is it feasible to clean the src dir before distributing? (i.e. remove the .o files)?

**Comment by umlaeute** [comment]
the [`autotools-mingw` PR](https://github.com/pure-data/pure-data/pull/275) does not include the object files anymore :-)

should this be closed?

**Comment by katjav** [comment]
The issue as such is solved. So it can be closed, but the comments by @danomatika and @rnkn still hold: `include` is the conventional location for header files. So if Pd provides that (with a copy of header files), pdlibbuilder could change the API search path accordingly after some time.
