### ISSUE TITLE
[Question] How to compile an external in windows.

### ISSUE THREAD

**Issue by rvega** [pure-data/pd-lib-builder#47]
Not familiar at all with Windows development tools. 
On Linux, I know I can just follow the instructions in the Readme of pd-lib-builder and then do `make` in a terminal and viola! 
What is the equivalent in Windows of `make`? I have installed Visual Studio 2017 and the C++ tools and those are working fine.  Do I need Mingw or Cygwin to compile an external? 
Also, I' m using Purrr Data, if that makes a difference.
Thanks in advance!

**Comment by Lucarda** [comment]
Hi,

With **pd-lib-builder** you should use Msys2 (or Msys1):

### Building On Windows With Msys2
Download the 64-bit installer from:

https://www.msys2.org/

Follow installation instructions on: https://github.com/msys2/msys2/wiki/MSYS2-installation

Add with pacman these packages:

`pacman -S make pkgconfig autoconf automake libtool`

### Then the 32-bit compiler:

`pacman -S mingw32/mingw-w64-i686-gcc`

### Optional For 64-Bit

The 64-bit compiler:

`pacman -S mingw64/mingw-w64-x86_64-gcc `

**Comment by umlaeute** [comment]
closing this as @Lucarda has answered it.
@katja: maybe this should go into the README

**Comment by rvega** [comment]
Thank you!
+1 Should go in Readme
