### ISSUE TITLE
can we build for macOS 10.6? ("symbol not found ___exp10")

### ISSUE THREAD

**Issue by porres** [pure-data/pd-lib-builder#52]
I sent this email to the Pd list and now I wonder if the issue is related to the fact we cannot build for 10.6 with pd-lib-builder, what you say?

here's the screenshot with the error of loading an external built with -pd-lib-builder in macOS 10.6.8
![unnamed](https://user-images.githubusercontent.com/5360142/59155567-77a15280-8a62-11e9-959c-b8aaf41b6f21.jpg)

**Comment by katjav** [comment]
There has been a regression bug where minimum OSX version was not specified by Makefilepdlibbuilder. This was supposed to be fixed with commit ece8e6b, and subsequent commit 1137cca sets 10.6 as minimum. That is the actual status quo now, but note that in issue #51 it is disputed whether pdlibbuilder should set that flag at all.

Anyway,  can you check:

- if current pdlibbuilder builds your library with option `-mmacosx-version-min=10.6`
- if that build works on 10.6

**Comment by porres** [comment]
ok, I'll try the latest/cuurent code from the last commit. It seems i used 0.50 when I compiled the thing that didn't work, that can probably explain this them huh?

And how about a new release to include this?

**Comment by porres** [comment]
So, I just got the latest code from the latest commit and recompiled it. The issue seemed to go away as tested by @umlaeute 

I couldn't use the -mmacosx-version-min=10.6 option, I just hit make install. Not sure how to use that flag, this is what happened when I tried it. Anyway, seems I just didn't need to set the target and so the flag would be redundanct, right?

<img width="759" alt="Screen Shot 2019-06-12 at 13 27 46" src="https://user-images.githubusercontent.com/5360142/59369133-1ef9e000-8d16-11e9-8e40-7a0494288d03.png">

**Comment by umlaeute** [comment]
@porres it seems like you are confusing *make* flags with *compiler* flags.

see the manpages for `make` and your compiler (`clang`, `gcc`).
also use your favorite web-search foo to learn a bit about "macosx-version-min".

but to conclude: the latest and greatest pd-lib-builder builds for OSX-10.6 *by default* for me.
So I guess the answer to your question is: yes, *we* can build for OSX-10.6.
However, Apple is fading out support for older systems quickly. So it might be that *you* cannot build for OSX-10.6 with the shiny new XCode.
