### ISSUE TITLE
pd.dll: file format not recognized

### ISSUE THREAD

**Issue by hyruuk** [pure-data/pd-lib-builder#53]
Hi,

I am trying to compile pd-psycho (https://github.com/porres/pd-psycho) on Windows10 with pd-vanilla (0.49.0) using pd-lib-builder but I keep encountering error messages that I don't really understand.

I am using MinGW to be able to use the "make" command under Windows. 
However, as soon as I use "make" in the pd-psycho folder, it returns this error : 
![69371075_399392444022904_2478048670679826432_n](https://user-images.githubusercontent.com/36450529/62881062-b6ae8700-bce3-11e9-9ea0-1e8288425146.png)

Since I explicitely refered to C:/Pd/bin, I can't understand why the command returns "C:/Pd/bin/pd.dll: file not recognized: file format not recognized". 

Do someone have an idea on how to fix this please ? What am I doing wrong ?

Thanks by advance

**Comment by Lucarda** [comment]
Hi,
It could be that you are using a 32-bit pd.dll and you are (as shown in the pic)  a 64-bit compiler.

Make sure your pd.dll matches your compiler.

also you can do: `make PDDIR=C:/Pd` this is one command instead of the two deprecated commands you are using

**Comment by hyruuk** [comment]
Thanks for your help !

I used Cygwin to check if pd.dll is 32 or 64-bit, and from what I understand, both pd.dll and my compiler are in 64-bit versions : 
`yann@DESKTOP-KP9KSJT /cygdrive/c/Pd/bin
$ file pd.dll
pd.dll: PE32+ executable (DLL) (console) x86-64 (stripped to external PDB), for MS Windows
`

Moreover, I'd like to try with a 32-bit version of pd.dll to check if this is indeed the source of the problem, but I can't find one.

**Comment by Lucarda** [comment]
hmm,

I have just compiled (https://github.com/porres/pd-psycho) on Windows10 with Msys2-MINGW64 and it worked fine.

See : http://msp.ucsd.edu/software.html for the "Stable" win 32 or 64 release.

Also check https://github.com/pure-data/pd-lib-builder/issues/47 on how to set a Msys2 compiler.

**Comment by katjav** [comment]
@hyruuk did you make any progress that could help identify a bug in pd-lib-builder?

**Comment by katjav** [comment]
Renamed the issue title to make this better retrievable.

**Comment by hyruuk** [comment]
@katjav Unfortunately not. I tried playing with the .dll's for a while with no success, then decided to switch to Linux (Mint 19), and it works flawlessly. I didn't try the solutions of #47 yet though. I might give it a go someday and post the result here. Thanks again for your help !

**Comment by katjav** [comment]
@hyruuk since we don't investigate further I'm closing this for now. Have fun with Linux.
