### ISSUE TITLE
doc not clear

### ISSUE THREAD

**Issue by FreaIsDead** [pure-data/pd-lib-builder#54]
could u give me basic example for creating a Makefile file for compiling the code for Windows.
For example, this is what i wrote for compiling on my Linux system:

~~~make
lib.name = mylib
class.sources = counter.c
include ../Makefile.pdlibbuilder
~~~

what should i write for creating a .dll and not a .pd_linux?

**Comment by katjav** [comment]
To build a .dll you should compile on Windows. As the `README.md` says:

> defines build settings based on autodetected OS and architecture

If you want to compile a .dll for Windows on Linux you must use a cross compiler and override some variables on command line as described in `tips-tricks.md`.

**Comment by umlaeute** [comment]
you should definitely read both `README.md` and `tips-tricks.md`.

afaict, all documentation you require is already there (including the tip to use a variable for the path to pd-lib-builder:

~~~make
PDLIBBUILDER_DIR=..
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
~~~
