### ISSUE TITLE
LDFLAGS?

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pd-lib-builder#6]
how can I add additional linker flags?

e.g. in Debian packages are routinely build with *hardening* enabled, which involves adding/overriding `CPPFLAGS`, `C(XX)FLAGS` and `LDFLAGS`.

**Comment by katjav** [comment]
Issues #5 and #6 are both addressed in test branch:

https://github.com/pure-data/pd-lib-builder/tree/command-line-build-flags

**Comment by umlaeute** [comment]
looks great.

**Comment by katjav** [comment]
Thanks for testing. Merged into master with commit  98f3582, version 0.2.1.

**Comment by katjav** [comment]
Deleted test branch command-line-build-flags.

**Comment by umlaeute** [comment]
afaik this issues has been resolved.
