### ISSUE TITLE
Static Linking and GPL license

### ISSUE THREAD

**Issue by emviveros** [pure-data/pd-lib-builder#67]
Hi! I don't know if here is the right place for questioning it, but here we are!

I´m working in compiling Cyclone and Else binaries. We have an [issue](https://github.com/porres/pd-else/issues/779) with glibc version at run binaries in ubuntu 18.04 (glibc 2.27). I´m compiling it in Ubuntu 20.04 (glibc 2.29). Since compiling it libs with pd-lib-builder I obtain dynamic link against glicb I think about static link glibc 2.29 using -static flag.

1. I´m looking about how to set this flag to pd-lib-builder avoiding to break other default assignaled flags.

2. If I have success in embbed glibc in external binaries this cause problems with the use of licenses that are more permissive than GPL when using these libs to make other softwares?

Maybe the best is downgrade glibc to 2.27 and offer support from linux system with this version? what is the standard procedure in distributing external binaries for these cases? How can I compile externals with the flag -static without mess default flags in lib-pd-builder?

Thanks!

**Comment by Lucarda** [comment]
I was waiting for someone with more experience than me on Linux gives an answer so that i can also learn. :)

I think you **should not** use the `-static` flag but you can do it with this lines in the Makefile:

```
define forLinux
	cflags += -static
	
endef
```

Again you **should not** use the `-static` flag.

Since I have provided much of the earlier `else & cyclone linux32/64 binaries` I don't understand why the issue you are referring has not happen before. The binaries I did were compiled with Debian10.

**Comment by emviveros** [comment]
Yes.. To avoid compile with -static and populate ram with glibc and run into licenses issues, I was opted to compile in ubuntu 18.04 once it will be suported by canonical until 2028 and yet I tested the binaries in Debian 10 and Ubuntu 20.04 successful.

I don't have idea why Debian 10 compilation works in Ubuntu 18.04 once Debian 10 use glibc 2.28-10 and Ubuntu 18 glibc 2.27-3ubuntu1.2. Maybe some witchcraft from canonical.. I really don't know..

@Lucarda why do you was opted for debian? Maybe I can review my decision...

**Comment by Lucarda** [comment]
> why do you was opted for debian? Maybe I can review my decision...

Because @umlaeute  use it.

:)

**Comment by emviveros** [comment]
Yes.. I agree.. This really is a good reason!

**Comment by emviveros** [comment]
> Because @umlaeute use it.

**Comment by Lucarda** [comment]
I use debian + xfce

:)
