### ISSUE TITLE
Enable setting flags for OS

### ISSUE THREAD

**Issue by residuum** [pure-data/pd-lib-builder#7]
For my library that I am migrating from the Pd extended library template to the pd-lib-builder Makefile, I need to set OS dependent flags.

Would it be OK to include variables like `windows.cflags`, ` linux.ldflags` and `mac.ldlibs`?

Are there any other variables that would make sense to make OS or even architecture dependent? I would implement that and file a pull request for it.

**Comment by danomatika** [comment]
What about using the 'system' variable provided by pd-lib-builder?

**Comment by danomatika** [comment]
Ah, never mind. system is not populated when including pd-lib-builder last. :P

**Comment by residuum** [comment]
It is for https://github.com/residuum/PuRestJson/blob/master/Makefile#L37 and following.

**Comment by katjav** [comment]
Thanks for bringing this topic up and sorry for the long response time. I'm cautious with introducing 'convenience variables' to Makefile.pdlibbuilder's 'API'. OS specific flags like windows.cflags are only a small subset of convenience variables that one could think of. Other categories could include OS specific sources, machine specific flags, machine specific sources, flags for certain OS-machine combinations...

My original thought was that a library makefile can do whatever check you want, and conditionally define any of the already supported variables. An extra call to uname doesn't really slow down a build. 

But literally duplicating a check feels stupid, and indeed the value for 'system' is not available from Makefile.pdlibbuilder before it is included. I've now figured out an approach where evaluation of multiline defines named 'forLinux', 'forDarwin', 'forWindows' are deferred so they can be conditionally evaluated depending on system as detected by Makefile.pdlibbuilder. These multiline defines could be used for any variable that was already supported. I'll push a branch featuring the method shortly.

**Comment by residuum** [comment]
That is a great idea. I like it and will try.

**Comment by reduzent** [comment]
I think this is an excellent design, flexible and clutter-free at the same time.

It works well for what I've tested. Thanks.

**Comment by katjav** [comment]
Thanks for testing reduzent. Assuming this will work for others too I've merged it into branch master with commit 3946ea5. For anyone who comes here later, here's an example how to use it:

    define forLinux
      cflags += -DLINUX
      class.sources += linuxthing.c
    endef

**Comment by katjav** [comment]
Deleted topic branch 'eval-system-specific-defines' which was merged into master.
