### ISSUE TITLE
Raspberry pi 0 / 1 wrong build flags

### ISSUE THREAD

**Issue by purewack** [pure-data/pd-lib-builder#71]
I've been trying to build a simple external for the pi0 which used float math, specifically division. After many crashes I noticed that the build flags were for an armv7 processor while the raspberry pi 0 v1.3 (not the new pi0 2) has an armv61 processor. 

Adding a '-m' flag the uname if check fixes the issue for me.

`ifeq ($(shell uname -m), armv6l)`

**Comment by umlaeute** [comment]
sidenote: it's an `armv6l` processor, not an `armv61`

personally, i think we should not invest too much time in autodetecting the PiZero, but rather document that it needs special handling.

**Comment by katjav** [comment]
Thanks for your report @purewack, and apologies for the delayed response. Your fix is implemented with commit 5c2e137.

Where autodetection is attempted it should be done properly.
