### ISSUE TITLE
Non-tilde objects also built when source file has no tilde in its name

### ISSUE THREAD

**Issue by alexdrymonitis** [pure-data/pd-lib-builder#80]
I recently tried to build the grambilib library (https://github.com/rickygraham/grambilib/tree/master), whose source files don't have a tilde in their name, even though all objects are signal objects, and the tilde is everywhere inside the source . With `make`, two objects per source file were built, one with tilde and one without it. For example, for grambiman.c, I got a grambiman~.pd_linux and a grambiman.pd_linux. The latter fails to load in Pd because there is no grambiman_setup function. The grambiman~.pd_linux loads fine.

Changing the names of the source files to include the tilde, compiles tilde objects only. This is with the latest makefile, 0.7.0, on Debian 12.

**Comment by umlaeute** [comment]
that seems to be a problem with grambilib's use of pd-lib-builder, and not with pd-lib-builder itself (which has all the features required to build e.g. `[grambiman]` from *grambiman.c* and `[grambiman~]` from *grambiman~.c*, but also `[grambiman~]` from *grambiman.c*, and `[grambiman]` from *grambiman~.c*)

i'm therefore closing this.

**Comment by alexdrymonitis** [comment]
Actually, I added pd-lib-builder to it. How should I go about using pd-lib-builder to build tilde objects only, from source files that don't have the tilde in their name?

**Comment by umlaeute** [comment]
by reading the docs :-) (that is: the master `Makefile.pdlibbuilder`)

https://github.com/pure-data/pd-lib-builder/blob/77525265694bac50ed94c5ef62ebbae680c72ab0/Makefile.pdlibbuilder#L127-L133
